### ISSUE TITLE
Add Loading animation

### ISSUE THREAD

**Issue by sideroad** [koikijs/kyoden#8]

**Comment by taka66** [comment]
更新しているアニメーション自体
何を更新しているかわかるアニメーション
をまずつくる

**Comment by taka66** [comment]
slackみたいな感じでKを書くようにしたい

**Comment by sideroad** [comment]
和を感じられるアニメーションにしたい

**Comment by taka66** [comment]
![kyoden](https://user-images.githubusercontent.com/5513724/33791773-fa8fd8fc-dcd4-11e7-8ca7-d312511b7526.png)
